#!/bin/sh

sysmodmap=/etc/X11/xinit/.Xmodmap
usermodmap="${XMODMAP:-$HOME/.Xmodmap}"

sysresources=/etc/X11/xinit/.Xresources
userresources="${XRESOURCES:-$HOME/.Xresources}"

# merge in defaults and keymaps

[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$userresources" ] && xrdb -merge "$userresources"

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

pgrep -x dunst > /dev/null || dunst &
pgrep -x picom > /dev/null || picom &

exec launch_dwm
