#! /bin/sh

pgrep -x panel > /dev/null || panel &
pgrep -x xsetroot > /dev/null || xsetroot -cursor_name left_ptr &
setwal

bspc monitor -d "" "" "" "ﱮ" "ﭮ"  "龎" ""

bspc config border_width         3
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Code desktop="^3"
bspc rule -a discord desktop="^5"
bspc rule -a Gnome-calculator state=floating
bspc rule -a Pcmanfm desktop="^4"
bspc rule -a Zathura state=tiled
