#! /bin/sh

pgrep -x panel > /dev/null || panel &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config focused_border_color "#fabd2f"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Code desktop="^3"
bspc rule -a discord desktop="^5"
bspc rule -a Gnome-calculator state=floating
